### ISSUE TITLE
Ignore commits by user

### ISSUE THREAD

**Issue by ctoestreich** [jenkinsci/github-organization-folder-plugin#46] opened 2017-05-05 15:53 UTC
There needs to be a way to include a user or list of users to exclude from triggering builds.  Currently there is no such field similar to the **Additional Behaviours->Polling ignores commits from certain users** feature in the git config.  Commits from our system user for tagging git are triggering infinite loops of builds as we can't ignore these.

**Comment by jglick** [comment] 2017-06-19 12:35
* this plugin is obsolete
* we use JIRA not GitHub issues
* anyway this is a duplicate of a JIRA issue

**Closed by jglick** 2017-06-19 12:35 UTC
